Algoritmo "Areadoquadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : área do quadrado, exibir o resultado
// Autor(a)    : Lia Alvarez
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
lado:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor do lado do quadrado : ")
leia(lado)
resultado<-lado*lado
escreva("O valor da área do quadrado é : ", resultado, "cm")

Fimalgoritmo